spring:
  application:
    name: gestao-restaurante
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: app
    password: change-me
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8080
